use crate::browser::{self, BrowserCookieItem, BrowserCookieResult};
use anyhow::{anyhow, Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};
use url::Url;

#[derive(Debug, Clone, Serialize, Deserialize)]
struct LegacyCookieFile {
    site_url: String,
    items: Vec<BrowserCookieItem>,
}

pub fn save_cookie_file(path: &Path, _site_url: &str, items: &[BrowserCookieItem]) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).context("创建 cookie 文件目录失败")?;
    }

    let mut out = String::new();
    out.push_str("# Netscape HTTP Cookie File\n");
    out.push_str("# This file was generated by zentao-cli.\n");
    out.push_str("# https://curl.se/docs/http-cookies.html\n\n");

    for it in items {
        let domain = if it.domain.is_empty() { "" } else { &it.domain };
        let include_subdomains = if domain.starts_with('.') {
            "TRUE"
        } else {
            "FALSE"
        };
        let secure = if it.secure { "TRUE" } else { "FALSE" };
        let expires_unix = browser::chrome_expires_utc_to_unix(it.expires_utc).max(0);
        let prefix = if it.http_only { "#HttpOnly_" } else { "" };
        out.push_str(&format!(
            "{}{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            prefix, domain, include_subdomains, it.path, secure, expires_unix, it.name, it.value
        ));
    }

    fs::write(path, out).with_context(|| format!("写入 cookie 文件失败: {}", path.display()))?;
    Ok(())
}

pub fn load_cookie_from_file(site_url: &str, path: &Path) -> Result<BrowserCookieResult> {
    let data =
        fs::read(path).with_context(|| format!("读取 cookie 文件失败: {}", path.display()))?;
    let file_items = parse_cookie_file(&data, path)?;

    let parsed = Url::parse(site_url).context("解析 URL 失败")?;
    let host = parsed
        .host_str()
        .ok_or_else(|| anyhow!("URL 缺少 host"))?
        .to_string();
    let site_path = normalize_path(parsed.path());

    let mut by_name: HashMap<String, BrowserCookieItem> = HashMap::new();
    for it in file_items {
        if !host_matches(&host, &it.domain) {
            continue;
        }
        if !site_path.starts_with(&normalize_path(&it.path)) {
            continue;
        }
        match by_name.get(&it.name) {
            Some(old) if old.path.len() >= it.path.len() => {}
            _ => {
                by_name.insert(it.name.clone(), it);
            }
        }
    }

    let mut items = Vec::new();
    let mut parts = Vec::new();
    for name in ["keepLogin", "za", "zentaosid", "zp"] {
        if let Some(item) = by_name.remove(name) {
            parts.push(format!("{}={}", item.name, item.value));
            items.push(item);
        }
    }

    let has_auth_cookie = items
        .iter()
        .any(|it| matches!(it.name.as_str(), "za" | "zentaosid" | "zp"));
    if !has_auth_cookie {
        return Err(anyhow!(
            "cookie 文件中未找到匹配站点的 za/zentaosid/zp: {}",
            path.display()
        ));
    }

    Ok(BrowserCookieResult {
        cookie_header: parts.join("; "),
        items,
        profile_path: path.display().to_string(),
    })
}

fn parse_cookie_file(data: &[u8], path: &Path) -> Result<Vec<BrowserCookieItem>> {
    let text = String::from_utf8(data.to_vec())
        .with_context(|| format!("cookie 文件不是有效 UTF-8: {}", path.display()))?;
    let trimmed = text.trim_start();
    if trimmed.starts_with('{') {
        let legacy: LegacyCookieFile = serde_json::from_str(&text)
            .with_context(|| format!("解析 cookie 文件失败: {}", path.display()))?;
        return Ok(legacy.items);
    }
    parse_netscape_cookie_file(&text)
}

fn parse_netscape_cookie_file(text: &str) -> Result<Vec<BrowserCookieItem>> {
    let now_secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|_| anyhow!("系统时间错误"))?
        .as_secs() as i64;
    let now_chrome = (now_secs + 11_644_473_600_i64) * 1_000_000_i64;

    let mut items = Vec::new();
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() {
            continue;
        }

        let mut http_only = false;
        let mut row = line;
        if let Some(stripped) = row.strip_prefix("#HttpOnly_") {
            http_only = true;
            row = stripped;
        } else if row.starts_with('#') {
            continue;
        }

        let cols: Vec<&str> = row.splitn(7, '\t').collect();
        if cols.len() < 7 {
            continue;
        }

        let secure = cols[3].eq_ignore_ascii_case("TRUE");
        let expires_unix = cols[4].parse::<i64>().unwrap_or(0).max(0);
        let expires_utc = if expires_unix == 0 {
            0
        } else {
            (expires_unix + 11_644_473_600_i64) * 1_000_000_i64
        };

        items.push(BrowserCookieItem {
            domain: cols[0].to_string(),
            path: cols[2].to_string(),
            secure,
            expires_utc,
            name: cols[5].to_string(),
            value: cols[6].to_string(),
            http_only,
            creation_utc: now_chrome,
            last_access_utc: now_chrome,
        });
    }
    Ok(items)
}

fn host_matches(target_host: &str, cookie_host: &str) -> bool {
    if cookie_host == target_host {
        return true;
    }
    if let Some(stripped) = cookie_host.strip_prefix('.') {
        return target_host == stripped || target_host.ends_with(&format!(".{stripped}"));
    }
    false
}

fn normalize_path(path: &str) -> String {
    let p = if path.is_empty() { "/" } else { path };
    if p.ends_with('/') {
        p.to_string()
    } else {
        format!("{p}/")
    }
}
